# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2024-05-01T15:44:12Z"
  name: thekubeground.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
    hostedZoneIDs:
    - Z08018352S11505ZLESNH
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-cluster-state-5582a348e45d656f/thekubeground.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-west-2a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.28.6
  masterPublicName: api.thekubeground.com
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://oidc-5582a348e45d656f/thekubeground.com/discovery/thekubeground.com
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  sshKeyName: thekubeground
  subnets:
  - cidr: 172.20.0.0/16
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-05-01T15:44:12Z"
  labels:
    kops.k8s.io/cluster: thekubeground.com
  name: control-plane-us-west-2a
spec:
  additionalUserData:
  - name: startup.sh
    type: text/x-shellscript
    content: |
        #!/bin/bash
        set -euxo pipefail
        snap install helm --classic
        snap install yq
        echo "source <(kubectl completion bash)" >> /home/ubuntu/.bashrc # add autocomplete permanently
        echo 'alias k=kubectl' >> /home/ubuntu/.bashrc
        echo 'complete -o default -F __start_kubectl k' >> /home/ubuntu/.bashrc
        helm completion bash > /etc/bash_completion.d/helm
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240126
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-05-01T15:44:12Z"
  labels:
    kops.k8s.io/cluster: thekubeground.com
  name: node-us-west-2a
spec:
  additionalUserData:
  - name: startup.sh
    type: text/x-shellscript
    content: |
        #!/bin/bash
        set -euxo pipefail
        echo "source <(kubectl completion bash)" >> /home/ubuntu/.bashrc # add autocomplete permanently
        echo 'alias k=kubectl' >> /home/ubuntu/.bashrc
        echo 'complete -o default -F __start_kubectl k' >> /home/ubuntu/.bashrc
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240126
  machineType: t3.small
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2a
