apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - image: {{ .Values.image }}
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
